# spring 설정
spring:

  # name
  application:
    name: product-service

  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        # sql readable format 출력 여부
        format_sql: true

        # time 설정
        jdbc:
          time_zone: Asia/Seoul
          
    # sql execute log 출력 여부
    show-sql: true

# port
server:
  port: 19093
  
# 유레카 서버 설정
eureka:
  client:

    # 기본 서비스 통신 URL 설정
    service-url:
      defaultZone: http://localhost:19090/eureka/